export const translationsPL = {
  'Directed by Viktar Kasilkin': 'Reżyseria: Viktar Kasilkin',
  SignUp: 'Rejestracja',
  LogIn: 'Logowanie',
  Users: 'Użytkownicy',
  LogOut: 'Wyloguj',
  Search: 'Szukaj',
  Username: 'Nazwa użytkownika',
  Password: 'Hasło',
  'Confirm Password': 'Potwierdź Hasło',
  Reset: 'Zrzut',
  'Oh snap! You got an error!': 'O kurde! Masz błąd!',
  LOGIN: 'LOGOWANIE',
  SIGNUP: 'REJESTRACJA',
  Login: 'Logowanie',
  Signup: 'Rejestracja',
  'Go back': 'Wróć',
  'Create Item': 'Utwórz Element',
  'Create Collection': 'Stwórz Kolekcję',
  Title: 'Tytuł',
  Theme: 'Temat',
  Description: 'Opis',
  Date: 'Data',
  Time: 'Czas',
  Comics: 'Komiksy',
  Cards: 'Karty',
  Figures: 'Figurki',
  'Select a category': 'Wybierz kategorię',
  'Add image': 'Add image',
  Close: 'Zamknij',
  Name: 'Nazwa',
  Type: 'Typ',
  max: 'max',
  'Additional Props': 'Dodatkowe Rekwizyty',
  'Add a new item property': 'Dodaj nową właściwość elementu',
  'Сhoose the name of the new property': 'Wybierz nazwę nowej nieruchomości',
  'Сhoose the type of the new property': 'Wybierz typ nowej nieruchomości',
  'Add new field': 'Dodaj nowe pole',
  'Admin-panel': 'Panel-admina',
  'Сonfirm your action': 'Potwierdź swoje działanie',
  'Are you sure you want to delete it?': 'Czy na pewno chcesz go usunąć?',
  No: 'Nie',
  Yes: 'Tak',
  'My page': 'Moja strona',
  'Largest Collections': 'Największe Kolekcje',
  'Last Added Items': 'Ostatnio Dodane Przedmioty',
  'select all': 'wybierz wszystko',
  '/deselect': '/usuń zaznaczenie',
  name: 'nazwa',
  id: 'id',
  password: 'hasło',
  isAdmin: 'isAdmin',
  isBlocked: 'isBlocked',
  avatar: 'avatar',
  Likes: 'Lubi',
  likes: 'lubi',
  Comments: 'Komentarze',
  Comment: 'Komentarz',
  comments: 'komentarze',
  Default: 'Default',
  'Sorting by': 'Sortowanie według',
  'More than': 'Więcej niż',
  'Enter tag name': 'Wpisz nazwę tagu',
  'Add tag': 'Dodaj tag',
  tags: 'tagi',
  Tags: 'Tagi',
  Files: 'Pliki',
  'Dragndrop images, or click to select files':
    'Przeciągnij i upuść obrazy lub Kliknij, aby wybrać pliki',
  'Write a comment': 'Napisz komentarz',
  'From User name': 'Od nazwy użytkownika',
  'No data found': 'Nie znaleziono danych',
  'Show More': 'Pokaż Więcej',
  'Show Less': 'Pokaż Mniej'
};
