export const translationsPL = {
  'Directed by Viktar Kasilkin': 'Reżyseria: Viktar Kasilkin',
  SignUp: 'Rejestracja',
  LogIn: 'Logowanie',
  Users: 'Użytkownicy',
  LogOut: 'Wyloguj',
  Search: 'Szukaj',
  Username: 'Nazwa użytkownika',
  Password: 'Hasło',
  'Confirm Password': 'Potwierdź Hasło',
  Reset: 'Zrzut',
  'Oh snap! You got an error!': 'O kurde! Masz błąd!',
  LOGIN: 'LOGOWANIE',
  SIGNUP: 'REJESTRACJA',
  Login: 'Logowanie',
  Signup: 'Rejestracja',
  'Go back': 'Wróć',
  'Create Item': 'Utwórz Element',
  'Create Collection': 'Stwórz Kolekcję',
  Title: 'Tytuł',
  Theme: 'Temat',
  Description: 'Opis',
  Date: 'Data',
  Time: 'Czas',
  Comics: 'Komiksy',
  Cards: 'Karty',
  Figures: 'Figurki',
  'Select a category': 'Wybierz kategorię',
  'Add image': 'Add image',
  Close: 'Zamknij',
  Name: 'Nazwa',
  Type: 'Typ',
  max: 'max',
  'Additional Props': 'Dodatkowe Rekwizyty',
  'Add a new item property': 'Dodaj nową właściwość elementu',
  'Сhoose the name of the new property': 'Wybierz nazwę nowej nieruchomości',
  'Сhoose the type of the new property': 'Wybierz typ nowej nieruchomości',
  'Add new field': 'Dodaj nowe pole',
  'Admin-panel': 'Panel-admina'
};
