export const translationsGB = {
  'Directed by Viktar Kasilkin': 'Directed by Viktar Kasilkin',
  SignUp: 'SignUp',
  LogIn: 'LogIn',
  Users: 'Users',
  LogOut: 'LogOut',
  search: 'search',
  Username: 'Username',
  Password: 'Password',
  'Confirm Password': 'Confirm Password',
  Reset: 'Reset',
  'Oh snap! You got an error!': 'Oh snap! You got an error!',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  'Go back': 'Go back',
  'Create Item': 'Create Item',
  'Create Collection': 'Create Collection',
  Title: 'Title',
  Theme: 'Theme',
  Description: 'Description',
  Time: 'Time',
  Date: 'Date',
  Comics: 'Comics',
  Cards: 'Cards',
  Figures: 'Figures',
  'Select a category': 'Select a category',
  'Add image': 'Add image',
  Close: 'Close',
  Name: 'Name',
  Type: 'Type',
  max: 'max',
  'Additional Props': 'Additional Props',
  'Add new item property': 'Add new item property',
  'Сhoose the name of the new property': 'Сhoose the name of the new property',
  'Сhoose the type of the new property': 'Сhoose the type of the new property',
  'Add new field': 'Add new field',
  'Admin-panel': 'Admin-panel'
};
