export const translationsGB = {
  'Directed by Viktar Kasilkin': 'Directed by Viktar Kasilkin',
  SignUp: 'SignUp',
  LogIn: 'LogIn',
  Users: 'Users',
  LogOut: 'LogOut',
  search: 'search',
  Username: 'Username',
  Password: 'Password',
  'Confirm Password': 'Confirm Password',
  Reset: 'Reset',
  'Oh snap! You got an error!': 'Oh snap! You got an error!',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  'Go back': 'Go back',
  'Create Item': 'Create Item',
  'Create Collection': 'Create Collection',
  Title: 'Title',
  Theme: 'Theme',
  Description: 'Description',
  Time: 'Time',
  Date: 'Date',
  Comics: 'Comics',
  Cards: 'Cards',
  Figures: 'Figures',
  'Select a category': 'Select a category',
  'Add image': 'Add image',
  Close: 'Close',
  Name: 'Name',
  Type: 'Type',
  max: 'max',
  'Additional Props': 'Additional Props',
  'Add new item property': 'Add new item property',
  'Сhoose the name of the new property': 'Сhoose the name of the new property',
  'Сhoose the type of the new property': 'Сhoose the type of the new property',
  'Add new field': 'Add new field',
  'Admin-panel': 'Admin-panel',
  'Сonfirm your action': 'Сonfirm your action',
  'Are you sure you want to delete it?': 'Are you sure you want to delete it?',
  No: 'No',
  Yes: 'Yes',
  'My page': 'My page',
  'Largest Collections': 'Largest Collections',
  'Last Added Items': 'Last Added Items',
  'select all': 'select all',
  '/deselect': '/deselect',
  name: 'name',
  id: 'id',
  password: 'password',
  isAdmin: 'isAdmin',
  isBlocked: 'isBlocked',
  avatar: 'avatar',
  Likes: 'Likes',
  likes: 'likes',
  Comments: 'Comments',
  Comment: 'Comment',
  comments: 'comments',
  Default: 'Default',
  'Sorting by': 'Sorting by',
  'More than': 'More than',
  'Enter tag name': 'Enter tag name',
  'Add tag': 'Add tag',
  tags: 'tags',
  Tags: 'Tags',
  Files: 'Files',
  'Dragndrop images, or click to select files':
    'Dragndrop images, or click to select files',
  'Write a comment': 'Write a comment',
  'From User name': 'From User name',
  'No data found': 'No data found',
  'Show More': 'Show More',
  'Show Less': 'Show Less',
  'Go to Home': 'Go to Home',
  'The page you are looking for not avaible!':
    'The page you are looking for not avaible!',
  "Look like you're lost": "Look like you're lost"
};
